### ISSUE TITLE
find_files_from_load_path undefined method

### ISSUE THREAD

**Issue by logicminds** [rvm/pluginator#11]
NoMethodError: undefined method `find_files_from_load_path' for Gem:Module
from vendor/bundle/ruby/2.0.0/gems/pluginator-1.4.1/lib/pluginator/autodetect/finder.rb:60:in `find_load_path_plugins'

This occurs in pry when doing the following:

```
require 'pluginator'
Pluginator.find('puppet-debugger')

```

**Comment by mpapis** [comment]
can I see `gem --version`

**Comment by logicminds** [comment]
Gem::VERSION
=> "2.0.14.1"

**Comment by logicminds** [comment]
Also confirmed that "2.6.11" works.

**Comment by mpapis** [comment]
fixed in https://github.com/rvm/pluginator/commit/e808ba70eceb683eef9661134f21238ffbe12162#diff-3540d0de3fdf1e9312d7d0e746ebae07R1

**Comment by mpapis** [comment]
1.5.0 released with the fix
