### ISSUE TITLE
use different plugin path

### ISSUE THREAD

**Issue by logicminds** [rvm/pluginator#13]
I am trying to fix another gem's problem that uses plugins and wanted to know if the pluginator could use a different path besides `lib/plugins/`.

I would like the lookup path to be 'lib/kitchen'  or 'lib/inspec' and since these tools are well established there is no way to change the plugin directory to `lib/plugins`

**Comment by logicminds** [comment]
This seems to hard code the path: https://github.com/rvm/pluginator/blob/master/lib/pluginator/autodetect/finder.rb#L47

https://github.com/rvm/pluginator/blob/master/lib/pluginator/autodetect/finder.rb#L84

**Comment by mpapis** [comment]
closing in favor of #15
